---
title: "NFT EDA"
author: "Tam Trinh"
date: '2022-05-06'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Import libraries
```{r}
library(tidyverse)
library(dplyr)
library(ggplot2)

```

Load dataset
```{r}

punk1 <- read.csv('punk_attribute_data/0-999.csv')
punk2 <- read.csv('punk_attribute_data/1000-1999.csv')
punk3 <- read.csv('punk_attribute_data/2000-2999.csv')
punk4 <- read.csv('punk_attribute_data/3000-3999.csv')
punk5 <- read.csv('punk_attribute_data/4000-4999.csv')
punk6 <- read.csv('punk_attribute_data/5000-5999.csv')
punk7 <- read.csv('punk_attribute_data/6000-6999.csv')
punk8 <- read.csv('punk_attribute_data/7000-7999.csv')
punk9 <- read.csv('punk_attribute_data/8000-8999.csv')
punk10 <- read.csv('punk_attribute_data/9000-9999.csv')

attr <- read.csv('punk_attribute_data/CryptoPunks Attributes - Accessories Type.csv')

```

Combine dataframe into one
```{r}
AllPunk <- rbind(punk1, punk2, punk3, punk4, punk5, punk6, punk7, punk8, punk9, punk10)

```


```{r}
class(AllPunk$accessories)

```


```{r}
x <- "Green Eye Shadow / Earring / Blonde Bob"
x_split <- strsplit(x, "/")
x_split
class(x_split[[1]])

y <- " Earring "

str_trim(y)


punktest <- AllPunk[1:10, ]
punktest$accessories <- sapply(punktest$accessories, strsplit(punktest$accessories, "/"))

```


```{r}
a_m1 <- apply(m1, 2, sum)


z<-data.frame(nam1=c("bbb / aba "," ccc / abb "," ddd / abc ","eee / abd "),stringsAsFactors=FALSE)

z$nam5 <- strsplit(z$nam1,split="/")

y <- unlist(z$nam5)
z$nam6[1] <- c(str_trim(y))



```


```{r}
y<-data.frame(nam1=c("aaa..aba","bbb..abb","ccc..abc","ddd..abd", "ddd..abd..abc"),
stringsAsFactors=FALSE)
library(stringr)

y$nam2<-as.data.frame(str_split_fixed(y$nam1, "\\..", 2))[[1]]
y$nam3<-as.data.frame(str_split_fixed(y$nam1, "\\..", 2))[[2]]
y$nam4<-as.data.frame(str_split_fixed(y$nam1, "\\..", 2))[[3]]

test <- c("bbb ", " aba ")
str_trim(test)
z$nam4[1]
z$nam4[1] <- unlist(z$nam4[1])
length(z$nam4[[1]])
z$nam4[[2]]




z$nam4 <- str_trim(z$nam2)
```


```{r}
```















